/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AdminUsersRouteImport } from './routes/admin-users'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as DiscountsRouteImport } from './routes/discounts'
import { Route as ImpersonationRouteImport } from './routes/impersonation'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SystemHealthRouteImport } from './routes/system-health'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as OwnersIndexRouteImport } from './routes/owners.index'
import { Route as OwnersOwnerIdRouteImport } from './routes/owners.$ownerId'
import { Route as OwnersNewRouteImport } from './routes/owners.new'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties.$propertyId'
import { Route as SupportIndexRouteImport } from './routes/support.index'
import { Route as SupportTicketIdRouteImport } from './routes/support.$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsRoute = DiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpersonationRoute = ImpersonationRouteImport.update({
  id: '/impersonation',
  path: '/impersonation',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemHealthRoute = SystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersIndexRoute = OwnersIndexRouteImport.update({
  id: '/owners/',
  path: '/owners/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersOwnerIdRoute = OwnersOwnerIdRouteImport.update({
  id: '/owners/$ownerId',
  path: '/owners/$ownerId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersNewRoute = OwnersNewRouteImport.update({
  id: '/owners/new',
  path: '/owners/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/properties/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportTicketIdRoute = SupportTicketIdRouteImport.update({
  id: '/support/$ticketId',
  path: '/support/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin-users': typeof AdminUsersRoute
  '/announcements': typeof AnnouncementsRoute
  '/audit': typeof AuditRoute
  '/discounts': typeof DiscountsRoute
  '/impersonation': typeof ImpersonationRoute
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRoute
  '/jobs': typeof JobsRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/plans': typeof PlansRoute
  '/revenue': typeof RevenueRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/system-health': typeof SystemHealthRoute
  '/usage': typeof UsageRoute
  '/owners/$ownerId': typeof OwnersOwnerIdRoute
  '/owners/new': typeof OwnersNewRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/owners/': typeof OwnersIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/support/': typeof SupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin-users': typeof AdminUsersRoute
  '/announcements': typeof AnnouncementsRoute
  '/audit': typeof AuditRoute
  '/discounts': typeof DiscountsRoute
  '/impersonation': typeof ImpersonationRoute
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRoute
  '/jobs': typeof JobsRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/plans': typeof PlansRoute
  '/revenue': typeof RevenueRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/system-health': typeof SystemHealthRoute
  '/usage': typeof UsageRoute
  '/owners/$ownerId': typeof OwnersOwnerIdRoute
  '/owners/new': typeof OwnersNewRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/owners': typeof OwnersIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/support': typeof SupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin-users': typeof AdminUsersRoute
  '/announcements': typeof AnnouncementsRoute
  '/audit': typeof AuditRoute
  '/discounts': typeof DiscountsRoute
  '/impersonation': typeof ImpersonationRoute
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRoute
  '/jobs': typeof JobsRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/plans': typeof PlansRoute
  '/revenue': typeof RevenueRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/system-health': typeof SystemHealthRoute
  '/usage': typeof UsageRoute
  '/owners/$ownerId': typeof OwnersOwnerIdRoute
  '/owners/new': typeof OwnersNewRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/owners/': typeof OwnersIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/support/': typeof SupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/admin-users'
    | '/announcements'
    | '/audit'
    | '/discounts'
    | '/impersonation'
    | '/integrations'
    | '/invoices'
    | '/jobs'
    | '/listings'
    | '/login'
    | '/notifications'
    | '/payments'
    | '/plans'
    | '/revenue'
    | '/roles'
    | '/settings'
    | '/staff'
    | '/subscriptions'
    | '/system-health'
    | '/usage'
    | '/owners/$ownerId'
    | '/owners/new'
    | '/properties/$propertyId'
    | '/support/$ticketId'
    | '/owners/'
    | '/properties/'
    | '/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/admin-users'
    | '/announcements'
    | '/audit'
    | '/discounts'
    | '/impersonation'
    | '/integrations'
    | '/invoices'
    | '/jobs'
    | '/listings'
    | '/login'
    | '/notifications'
    | '/payments'
    | '/plans'
    | '/revenue'
    | '/roles'
    | '/settings'
    | '/staff'
    | '/subscriptions'
    | '/system-health'
    | '/usage'
    | '/owners/$ownerId'
    | '/owners/new'
    | '/properties/$propertyId'
    | '/support/$ticketId'
    | '/owners'
    | '/properties'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/admin-users'
    | '/announcements'
    | '/audit'
    | '/discounts'
    | '/impersonation'
    | '/integrations'
    | '/invoices'
    | '/jobs'
    | '/listings'
    | '/login'
    | '/notifications'
    | '/payments'
    | '/plans'
    | '/revenue'
    | '/roles'
    | '/settings'
    | '/staff'
    | '/subscriptions'
    | '/system-health'
    | '/usage'
    | '/owners/$ownerId'
    | '/owners/new'
    | '/properties/$propertyId'
    | '/support/$ticketId'
    | '/owners/'
    | '/properties/'
    | '/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AuditRoute: typeof AuditRoute
  DiscountsRoute: typeof DiscountsRoute
  ImpersonationRoute: typeof ImpersonationRoute
  IntegrationsRoute: typeof IntegrationsRoute
  InvoicesRoute: typeof InvoicesRoute
  JobsRoute: typeof JobsRoute
  ListingsRoute: typeof ListingsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentsRoute: typeof PaymentsRoute
  PlansRoute: typeof PlansRoute
  RevenueRoute: typeof RevenueRoute
  RolesRoute: typeof RolesRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  SystemHealthRoute: typeof SystemHealthRoute
  UsageRoute: typeof UsageRoute
  OwnersOwnerIdRoute: typeof OwnersOwnerIdRoute
  OwnersNewRoute: typeof OwnersNewRoute
  PropertiesPropertyIdRoute: typeof PropertiesPropertyIdRoute
  SupportTicketIdRoute: typeof SupportTicketIdRoute
  OwnersIndexRoute: typeof OwnersIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-users': {
      id: '/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts': {
      id: '/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof DiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impersonation': {
      id: '/impersonation'
      path: '/impersonation'
      fullPath: '/impersonation'
      preLoaderRoute: typeof ImpersonationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-health': {
      id: '/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof SystemHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners/': {
      id: '/owners/'
      path: '/owners'
      fullPath: '/owners/'
      preLoaderRoute: typeof OwnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners/$ownerId': {
      id: '/owners/$ownerId'
      path: '/owners/$ownerId'
      fullPath: '/owners/$ownerId'
      preLoaderRoute: typeof OwnersOwnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners/new': {
      id: '/owners/new'
      path: '/owners/new'
      fullPath: '/owners/new'
      preLoaderRoute: typeof OwnersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$propertyId': {
      id: '/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/$ticketId': {
      id: '/support/$ticketId'
      path: '/support/$ticketId'
      fullPath: '/support/$ticketId'
      preLoaderRoute: typeof SupportTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AdminUsersRoute: AdminUsersRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AuditRoute: AuditRoute,
  DiscountsRoute: DiscountsRoute,
  ImpersonationRoute: ImpersonationRoute,
  IntegrationsRoute: IntegrationsRoute,
  InvoicesRoute: InvoicesRoute,
  JobsRoute: JobsRoute,
  ListingsRoute: ListingsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  PlansRoute: PlansRoute,
  RevenueRoute: RevenueRoute,
  RolesRoute: RolesRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  SystemHealthRoute: SystemHealthRoute,
  UsageRoute: UsageRoute,
  OwnersOwnerIdRoute: OwnersOwnerIdRoute,
  OwnersNewRoute: OwnersNewRoute,
  PropertiesPropertyIdRoute: PropertiesPropertyIdRoute,
  SupportTicketIdRoute: SupportTicketIdRoute,
  OwnersIndexRoute: OwnersIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
